# AUTOGENERATED! DO NOT EDIT! File to edit: 95_salary_negotiations.ipynb (unless otherwise specified).

__all__ = ['get_uk_takehome_salary', 'USD2GBP', 'get_salary_bands']

import pandas as pd
import numpy as np

USD2GBP = 0.8

def get_uk_takehome_salary(gbp_salary):
    basic = (12_571, 50_270) # 20%
    higher = (50_271, 150_000) # 40%
    additional = (150_001, 999_000) # 45%

    # calculate the tax free amount
    tax_free = min([max([12_570 - (gbp_salary - 100_000)/2, 0]), 12_570])

    income = {
        'tax_free': tax_free,
        'basic': 0,
        'higher': 0,
        'additional': 0
        }
    if gbp_salary > basic[0]:
        relevant_section = min([basic[1], gbp_salary])
        income['basic'] = min([relevant_section - tax_free, basic[1]]) * 0.8
    if gbp_salary > higher[0]:
        relevant_section = min([higher[1], gbp_salary])
        income['higher'] = min([relevant_section - basic[1], higher[1]]) * 0.6
    if gbp_salary > additional[0]:
        relevant_section = min([additional[1], gbp_salary])
        income['additional'] = int(min([relevant_section - higher[1], additional[1]]) * 0.55)

    taxes = {
        "taxes_basic": int(income['basic'] * 0.2),
        "taxes_higher": int(income['higher'] * 0.4),
        "taxes_additional": int(income['additional'] * 0.45),
        "taxes_free": int(min([ 12_570 - tax_free, 12_570]) * 0.2)
    }
    return {**income, **taxes}

def get_salary_bands(salary):
    smin, smax = max(salary - 100_000, 0), salary + 140_000
    salaries = [ get_uk_takehome_salary(x) for x in range(smin, smax, 1000) ]
    df = pd.DataFrame(salaries)
    return df